# Generated by Django 3.2 on 2022-05-29 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20220523_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='зафиксированная цена'),
            preserve_default=False,
        ),
    ]
