# Generated by Django 3.2 on 2022-06-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_basket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('START', 'принят'), ('WORK', 'в работе'), ('CANCEL', 'отменен'), ('FINISH', 'завершен')], default='START', max_length=10, verbose_name='Статус'),
        ),
    ]
