# Generated by Django 3.2 on 2022-06-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('START', 'принят'), ('WORK', 'в работе'), ('CANCEL', 'отменен'), ('FINISH', 'завершен')], db_index=True, default='START', max_length=10, verbose_name='Статус'),
        ),
    ]
