# Generated by Django 3.2 on 2022-06-02 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время созвона'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='registrated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время регистрации'),
        ),
    ]
