# Generated by Django 3.2 on 2022-06-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20220602_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'наличные'), ('ELEСTRON', 'безналичные'), ('UNDEFINED', '-не указано')], db_index=True, default='UNDEFINED', max_length=10, verbose_name='Оплата'),
        ),
    ]
