# Generated by Django 3.2 on 2022-06-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_restaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='OrderedProduct',
        ),
    ]
